
title: XForum Page
theme: jekyll-theme-slate
show_downloads: true
description: XForum is a open source forum written by golang.
site:
  github:
    url: https://github.com/goxforum/xforum
#    zip_url: https://github.com/goxforum/xforum/download.zip
